import { Hexagon } from 'lucide-react';

export const SignalGeneration = () => {
  return (
    <section className="py-32 px-6 max-w-7xl mx-auto relative z-10 overflow-hidden">
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-20 items-center">
        <div className="space-y-8">
          <h2 className="font-headline text-5xl font-bold leading-tight">Signal Generation <br/><span className="text-primary-container">Evolved</span></h2>
          <p className="text-on-surface-variant text-lg leading-relaxed font-light">
            Our signals aren't just data points. They are multifaceted predictions generated by our proprietary holographic transformer engine. Each signal carries its own weight of probability, confidence, and real-time execution depth.
          </p>
          <div className="space-y-6">
            <div className="flex items-center gap-5 p-4 rounded-2xl glass-panel glass-stroke group transition-all duration-300 hover:bg-white/5">
              <div className="w-12 h-12 rounded-xl bg-primary-container/10 flex items-center justify-center border border-primary-container/20 group-hover:scale-110 transition-transform">
                <Hexagon className="text-primary-container" size={24} />
              </div>
              <div>
                <h4 className="font-bold text-on-surface">Multifaceted Analysis</h4>
                <p className="text-sm text-neutral-500">Processing 128 data vectors per signal.</p>
              </div>
            </div>
            <div className="flex items-center gap-5 p-4 rounded-2xl glass-panel glass-stroke group transition-all duration-300 hover:bg-white/5">
              <div className="w-12 h-12 rounded-xl bg-secondary-container/10 flex items-center justify-center border border-secondary-container/20 group-hover:scale-110 transition-transform">
                <span className="material-symbols-outlined text-secondary">verified</span>
              </div>
              <div>
                <h4 className="font-bold text-on-surface">On-Chain Verification</h4>
                <p className="text-sm text-neutral-500">Every signal timestamped on the blockchain.</p>
              </div>
            </div>
          </div>
        </div>
        {/* 3D Mockup Container */}
        <div className="relative flex items-center justify-center min-h-[500px]">
          {/* The AI Signal Holographic Mockup */}
          <div className="relative w-72 h-72 z-20 group">
            <div className="absolute inset-0 bg-primary-container/20 rounded-full blur-[80px] animate-pulse"></div>
            {/* Central Node / Holographic Crystal Representation */}
            <div className="absolute inset-0 flex items-center justify-center">
              <div className="w-48 h-48 relative animate-spin-slow">
                <div className="absolute inset-0 border-2 border-primary-container/30 rotate-45 rounded-lg"></div>
                <div className="absolute inset-0 border-2 border-secondary-container/30 -rotate-45 rounded-lg"></div>
                <div className="absolute inset-4 border border-white/20 rounded-full"></div>
                <div className="absolute inset-0 flex items-center justify-center">
                  <span className="material-symbols-outlined text-7xl text-white drop-shadow-[0_0_20px_#00f0ff] animate-float">view_in_ar</span>
                </div>
              </div>
            </div>
            {/* 3D Particle Nodes */}
            <div className="absolute -top-10 -left-10 w-8 h-8 glass-panel glass-stroke rounded-lg shard animate-float" style={{animationDelay: '-1s'}}></div>
            <div className="absolute bottom-4 -right-12 w-12 h-12 glass-panel glass-stroke rounded-full animate-float-slow" style={{animationDelay: '-2s'}}></div>
          </div>
          {/* Physically Paired Profit Card */}
          <div className="absolute bottom-0 right-0 lg:-right-8 z-30 transform hover:translate-y-[-10px] transition-transform duration-500">
            <div className="glass-panel border-l-4 border-l-primary-container p-6 rounded-2xl shadow-2xl backdrop-blur-3xl w-64">
              <div className="flex justify-between items-center mb-4">
                <span className="text-[10px] font-black uppercase tracking-[0.2em] text-neutral-500">Signal #8241A</span>
                <div className="px-2 py-0.5 rounded bg-primary-container/10 text-primary-container text-[10px] font-bold">VERIFIED</div>
              </div>
              <div className="text-xs text-neutral-400 mb-1">Profit Secured</div>
              <div className="text-5xl font-headline font-bold text-primary-container tracking-tighter mb-4">+89.42%</div>
              <div className="flex items-center gap-2 text-[10px] text-neutral-500">
                <span className="material-symbols-outlined text-xs">schedule</span>
                <span>Executed in 1.4s</span>
              </div>
              <div className="mt-4 h-1 w-full bg-white/5 rounded-full overflow-hidden">
                <div className="h-full bg-primary-container w-[100%] shadow-[0_0_10px_#00f0ff]"></div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
};
